apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcname }}
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
